name: ci-stylelint
on: [pull_request]
jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "assets/css/*.scss"
          INDENT_SPACES: 4
          PATTERN: "_sass/*.scss"
          INDENT_SPACES: 4
